name: Show Info

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Show kernel version
        run: uname -a

      - name: Find kernel module files
        run: sudo find / -name *.ko*

      - name: list /usr/src/
        run: ls -la /usr/src/*

      - name: Show .config
        run: find /usr/src/ -name .config -exec cat {} \;

      - name: Add can kernel module
        run: sudo modprobe can

      - name: Add can-raw kernel module
        run: sudo modprobe can-raw

      - name: Add vcan kernel module
        run: sudo modprobe vcan
