name: Show Info

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Show kernel version
        run: uname -a

      - name: Find CAN kernel module files
        run: find /lib/modules -name *can*

      - name: list /usr/src/
        run: ls -la /usr/src/*

      - name: Show .config
        run: cat /usr/src/linux-headers-6.8.0-1020-azure/.config

      - name: Add can kernel module
        run: sudo modprobe can

      - name: Add can-raw kernel module
        run: sudo modprobe can-raw

      - name: Add vcan kernel module
        run: sudo modprobe vcan
