name: Show Info

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Show kernel info - all
        run: uname -a

      - name: Show kernel release
        run: uname -r

      - name: Install linux-modules-extra-$(uname -r)
        run: sudo apt install linux-modules-extra-$(uname -r)

      - name: Find kernel module files
        run: sudo find / -name *.ko*

      - name: list /usr/src/
        run: ls -la /usr/src/*

      - name: Show .config
        run: find /usr/src/ -name .config -exec cat {} \;

      - name: Add can kernel module
        run: sudo modprobe can

      - name: Add can-raw kernel module
        run: sudo modprobe can-raw

      - name: Add vcan kernel module
        run: sudo modprobe vcan

      - name: Create vcan0
        run: sudo ip link add dev vcan0 type vcan

      - name: Set vcan0 mtu 16
        run: sudo ip link set vcan0 mtu 16

      - name: Set vcan0 up
        run: sudo ip link set up vcan0

      - name: Show interfaces
        run: ip a
